// Generated by scripts/write-git-log.mjs before Astro builds.
// Keep this file committed so dev builds have a stable fallback.
export const gitLog = [
  {
    "hash": "377e71e",
    "message": "Add universe dial switcher with cross-document view transitions"
  },
  {
    "hash": "73549e4",
    "message": "added terminal window controls to minimize, close, and expand the terminal"
  },
  {
    "hash": "c61ae73",
    "message": "added support for Pretext"
  },
  {
    "hash": "2d9dddb",
    "message": "Update headshot image with higher resolution version"
  },
  {
    "hash": "ebb9a8b",
    "message": "Add data-astro-reload to version switcher links"
  },
  {
    "hash": "cb6118d",
    "message": "Add transition-colors duration-2000 to terminal window elements"
  },
  {
    "hash": "45010c3",
    "message": "Adjust theme toggle transition duration to 2000ms"
  },
  {
    "hash": "2fe246d",
    "message": "Add Cloudflare Workers configuration"
  },
  {
    "hash": "1ed0036",
    "message": "Add version switcher UI for multi-version portfolio routing"
  },
  {
    "hash": "bb229fe",
    "message": "Update contact email, add Formspree endpoint, replace favicon"
  },
  {
    "hash": "e34b2f8",
    "message": "Version C (Terminal): CLI-themed portfolio"
  },
  {
    "hash": "2fb6a79",
    "message": "Initial commit: Astro portfolio site for seanmh.com"
  }
] as const;
