import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = resolve(root, 'src/content/git-log.ts');

function readGitLog() {
  try {
    const raw = execFileSync('git', ['log', '--oneline', '-n', '20'], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();

    if (!raw) return [];

    return raw.split('\n').map((line) => {
      const [hash, ...message] = line.trim().split(/\s+/);
      return {
        hash,
        message: message.join(' '),
      };
    });
  } catch {
    return [
      {
        hash: 'local',
        message: 'git history unavailable during this build',
      },
    ];
  }
}

const gitLog = readGitLog();
const source = `// Generated by scripts/write-git-log.mjs before Astro builds.\n// Keep this file committed so dev builds have a stable fallback.\nexport const gitLog = ${JSON.stringify(gitLog, null, 2)} as const;\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, source);
